// 文脈: 出力形式、設問、構成パーツ、初期状態の定義。
export const outputTypes = ["SPEC", "DESIGN", "AGENTS", "PROMPT", "PROMPT_FOR_SKILL"] as const;

export type OutputType = (typeof outputTypes)[number];
export type AnswerVolume = "quick" | "standard" | "deep";
export type QuestionInputType = "single" | "multi";

export const outputQuestionSections: Record<OutputType, readonly string[]> = {
	SPEC: [
		"目的・対象",
		"利用者・課題",
		"スコープ・優先度",
		"機能・画面",
		"データ・権限",
		"非機能・制約",
		"用途別設問",
		"検証・リリース",
	],
	DESIGN: [
		"目的・対象",
		"印象・世界観",
		"色・文字・質感",
		"構成・情報設計",
		"UIパーツ・操作感",
		"動き・演出",
		"用途別設問",
		"技術・制約",
	],
	AGENTS: ["行動原則", "技術スタック", "コマンド", "コーディング規約", "実行ルール", "禁止事項"],
	PROMPT: ["役割・前提", "タスク内容", "出力形式", "判断・質問方針", "品質基準"],
	PROMPT_FOR_SKILL: ["発動条件", "対象・前提", "作業手順", "ツール・参照", "例外処理"],
} as const;

export interface OutputTypeOption {
	id: OutputType;
	label: string;
	title: string;
	description: string;
	fileName: string;
}

export interface QuestionOption {
	id: string;
	label: string;
	partIds?: string[];
}

export interface QuestionCard {
	id: string;
	outputType: OutputType;
	section: string;
	layer?: string;
	title: string;
	prompt: string;
	inputType: QuestionInputType;
	volume: AnswerVolume[];
	options: QuestionOption[];
	freeTextLabel: string;
}

export interface QuestionAnswer {
	selectedOptionIds: string[];
	freeText: string;
}

export interface DocumentPart {
	id: string;
	outputType: OutputType;
	title: string;
	body: string;
}

export interface DocumentDraftState {
	outputType: OutputType;
	answerVolume: AnswerVolume;
	showUnansweredAnswers: boolean;
	globalFreeText: string;
	answers: Record<string, QuestionAnswer>;
	selectedPartIds: string[];
	generatedMarkdown: string;
}

export interface DocumentState extends DocumentDraftState {
	outputOptions: OutputTypeOption[];
	questions: QuestionCard[];
	visibleQuestions: QuestionCard[];
	parts: DocumentPart[];
	selectedParts: DocumentPart[];
	currentOutput: OutputTypeOption;
	setOutputType: (outputType: OutputType) => void;
	setAnswerVolume: (answerVolume: AnswerVolume) => void;
	setShowUnansweredAnswers: (value: boolean) => void;
	setGlobalFreeText: (value: string) => void;
	setQuestionFreeText: (questionId: string, value: string) => void;
	toggleQuestionOption: (questionId: string, optionId: string) => void;
	togglePart: (partId: string) => void;
	copyMarkdown: () => Promise<void>;
	downloadMarkdown: () => void;
}

export interface DocumentStateProps {
	state: DocumentState;
	className?: string;
}

export type ActionBarProps = DocumentStateProps;
export type SideNavProps = DocumentStateProps;
export type IntakePanelProps = DocumentStateProps;
export type OutputPanelProps = DocumentStateProps;

export const outputOptions: OutputTypeOption[] = [
	{
		id: "SPEC",
		label: "SPEC.md",
		title: "Markdown本文",
		description: "要件定義を整理する",
		fileName: "SPEC.md",
	},
	{
		id: "DESIGN",
		label: "DESIGN.md",
		title: "Markdown本文",
		description: "デザイン方針を整理する",
		fileName: "DESIGN.md",
	},
	{
		id: "AGENTS",
		label: "AGENTS.md",
		title: "Markdown本文",
		description: "エージェントルールを整理する",
		fileName: "AGENTS.md",
	},
	{
		id: "PROMPT",
		label: "PROMPT",
		title: "プロンプト本文",
		description: "AIへ渡す指示を整理する",
		fileName: "PROMPT.md",
	},
	{
		id: "PROMPT_FOR_SKILL",
		label: "PROMPT for SKILL.md",
		title: "プロンプト本文",
		description: "SKILL.md作成用の指示を整理する",
		fileName: "PROMPT_FOR_SKILL.md",
	},
];

export const parts: DocumentPart[] = [
	{
		id: "background",
		outputType: "SPEC",
		title: "背景・目的",
		body: "## 背景・目的\n\n- 解決したい課題と、このプロンプトで決めたいことを明記する。",
	},
	{
		id: "scope",
		outputType: "SPEC",
		title: "対象範囲",
		body: "## 対象範囲\n\n- MVPで含める範囲と、後回しにする範囲を分けて記載する。",
	},
	{
		id: "requirements",
		outputType: "SPEC",
		title: "機能要件",
		body: "## 機能要件\n\n- ユーザー操作、画面、データ、状態変化を確認できる粒度で列挙する。",
	},
	{
		id: "design_direction",
		outputType: "DESIGN",
		title: "デザイン方針",
		body: "## デザイン方針\n\n- 第一印象、トーン、情報密度、避けたい表現を判断基準として整理する。",
	},
	{
		id: "visual_system",
		outputType: "DESIGN",
		title: "ビジュアルシステム",
		body: "## ビジュアルシステム\n\n- 色、書体、余白、画像、UI状態の扱いを実装可能な粒度で定義する。",
	},
	{
		id: "motion_policy",
		outputType: "DESIGN",
		title: "モーション方針",
		body: "## モーション方針\n\n- 動きの役割、強度、パフォーマンス制約、代替表現を明記する。",
	},
	{
		id: "agent_principles",
		outputType: "AGENTS",
		title: "行動原則",
		body: "## 行動原則\n\n- 優先順位、判断基準、ユーザーへの確認が必要な条件を定義する。",
	},
	{
		id: "edit_rules",
		outputType: "AGENTS",
		title: "編集ルール",
		body: "## 編集ルール\n\n- 担当範囲、既存変更の扱い、禁止操作、ファイル編集前の確認手順を明記する。",
	},
	{
		id: "verification",
		outputType: "AGENTS",
		title: "検証方針",
		body: "## 検証方針\n\n- 実行すべきテスト、目視確認、失敗時の報告内容を定義する。",
	},
	{
		id: "role_context",
		outputType: "PROMPT",
		title: "役割と前提",
		body: "あなたの役割、対象読者、前提条件、制約を先に確認し、その範囲で回答してください。",
	},
	{
		id: "output_contract",
		outputType: "PROMPT",
		title: "出力形式",
		body: "出力は指定された見出し構造、粒度、表や箇条書きの使用条件、禁止事項に従ってください。",
	},
	{
		id: "question_policy",
		outputType: "PROMPT",
		title: "質問方針",
		body: "不明点は質問する条件と、仮定して進めてよい条件を分けて扱ってください。",
	},
	{
		id: "skill_trigger",
		outputType: "PROMPT_FOR_SKILL",
		title: "発動条件",
		body: "どのユーザー依頼でスキルを使うか、使わない条件も含めて定義してください。",
	},
	{
		id: "skill_workflow",
		outputType: "PROMPT_FOR_SKILL",
		title: "手順",
		body: "参照、判断、実行、検証、報告の流れを再現可能な順序で書いてください。",
	},
	{
		id: "skill_fallback",
		outputType: "PROMPT_FOR_SKILL",
		title: "例外処理",
		body: "必要な情報が不足した場合、ツールが使えない場合、失敗時の扱いを明記してください。",
	},
];

export const questions: QuestionCard[] = [
	{
		id: "spec_artifact_type",
		outputType: "SPEC",
		section: "目的・対象",
		title: "成果物タイプ",
		prompt: "今回定義する成果物の種類を選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "website", label: "Webサイト / LP", partIds: ["background", "scope"] },
			{ id: "web_app", label: "Webアプリ / SaaS", partIds: ["background", "requirements"] },
			{ id: "admin", label: "管理画面 / 社内ツール", partIds: ["background", "requirements"] },
			{ id: "commerce", label: "EC / 予約 / 申込", partIds: ["scope", "requirements"] },
			{ id: "ai_tool", label: "AIツール / 自動化", partIds: ["requirements", "verification"] },
			{ id: "api", label: "API / バックエンド", partIds: ["requirements", "verification"] },
			{ id: "feature", label: "既存機能の追加・改修", partIds: ["scope", "requirements"] },
		],
		freeTextLabel: "成果物名、既存環境、補足",
	},
	{
		id: "spec_goal",
		outputType: "SPEC",
		section: "目的・対象",
		title: "達成したい目的",
		prompt: "この要件定義で達成したい主目的を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "launch", label: "新規公開・新規提供を行う", partIds: ["background"] },
			{ id: "conversion", label: "問い合わせ・購入・登録を増やす", partIds: ["background", "requirements"] },
			{ id: "efficiency", label: "業務時間や手戻りを減らす", partIds: ["background", "requirements"] },
			{ id: "quality", label: "品質・安定性・保守性を上げる", partIds: ["verification"] },
			{ id: "integration", label: "既存システムや外部サービスと連携する", partIds: ["requirements"] },
			{ id: "validation", label: "仮説検証やMVP検証を行う", partIds: ["scope", "verification"] },
		],
		freeTextLabel: "成功とみなす状態、KPI、背景",
	},
	{
		id: "spec_background",
		outputType: "SPEC",
		section: "目的・対象",
		title: "背景・きっかけ",
		prompt: "今回の要件定義が必要になった背景を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "new_business", label: "新しい事業・企画を始める" },
			{ id: "user_request", label: "利用者や顧客から要望がある" },
			{ id: "internal_issue", label: "既存業務に非効率や属人化がある" },
			{ id: "current_limit", label: "既存サイトや機能に限界がある" },
			{ id: "technical_debt", label: "技術的負債や運用負荷を下げたい" },
			{ id: "compliance", label: "規約・法務・セキュリティ対応が必要" },
		],
		freeTextLabel: "現状、問題の発生頻度、関係者",
	},
	{
		id: "spec_users",
		outputType: "SPEC",
		section: "利用者・課題",
		title: "主な利用者",
		prompt: "主に誰が使うものですか。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "visitor", label: "一般の訪問者・見込み顧客" },
			{ id: "member", label: "ログイン済みユーザー・会員" },
			{ id: "operator", label: "運用担当者・管理者" },
			{ id: "sales", label: "営業・CS・サポート担当者" },
			{ id: "developer", label: "開発者・外部システム" },
			{ id: "executive", label: "意思決定者・レビュー担当者" },
		],
		freeTextLabel: "ペルソナ、利用頻度、利用環境",
	},
	{
		id: "spec_user_problem",
		outputType: "SPEC",
		section: "利用者・課題",
		title: "解決したい課題",
		prompt: "利用者や運用側のどの課題を解決しますか。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "hard_to_find", label: "必要な情報にたどり着けない" },
			{ id: "manual_work", label: "手作業・転記・確認作業が多い" },
			{ id: "mistakes", label: "入力ミスや対応漏れが起きやすい" },
			{ id: "slow_response", label: "対応や処理に時間がかかる" },
			{ id: "low_conversion", label: "申込・購入・問い合わせにつながらない" },
			{ id: "low_visibility", label: "状況や成果が見えにくい" },
			{ id: "maintenance_cost", label: "更新や保守に手間がかかる" },
		],
		freeTextLabel: "具体例、現在の代替手段、困っている場面",
	},
	{
		id: "spec_user_flow",
		outputType: "SPEC",
		section: "利用者・課題",
		title: "主要な利用シナリオ",
		prompt: "特に整理したい利用シナリオを選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "discover", label: "情報を探して内容を理解する" },
			{ id: "compare", label: "選択肢を比較して判断する" },
			{ id: "submit", label: "フォームや申込を完了する" },
			{ id: "manage", label: "データを登録・編集・削除する" },
			{ id: "monitor", label: "状況を確認し、必要な対応を行う" },
			{ id: "export", label: "結果を出力・共有・連携する" },
		],
		freeTextLabel: "開始条件、完了条件、例外フロー",
	},
	{
		id: "spec_scope",
		outputType: "SPEC",
		section: "スコープ・優先度",
		title: "対象範囲",
		prompt: "今回のMVPまたは初期版に含める範囲を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "public_view", label: "公開ページ・閲覧導線", partIds: ["scope"] },
			{ id: "auth", label: "ログイン・認証", partIds: ["requirements"] },
			{ id: "crud", label: "登録・編集・削除", partIds: ["requirements"] },
			{ id: "search_filter", label: "検索・絞り込み・並び替え", partIds: ["requirements"] },
			{ id: "form", label: "フォーム送信・申込", partIds: ["requirements"] },
			{ id: "notification", label: "通知・メール・リマインド", partIds: ["requirements"] },
			{ id: "admin", label: "管理画面・運用機能", partIds: ["requirements"] },
			{ id: "external", label: "外部連携・API", partIds: ["requirements"] },
		],
		freeTextLabel: "含める範囲、含めない範囲",
	},
	{
		id: "spec_out_of_scope",
		outputType: "SPEC",
		section: "スコープ・優先度",
		title: "後回しにする範囲",
		prompt: "初期版では後回しにするものを選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "payment", label: "決済・請求" },
			{ id: "multi_language", label: "多言語対応" },
			{ id: "advanced_admin", label: "高度な管理機能" },
			{ id: "automation", label: "自動化・AI連携" },
			{ id: "analytics", label: "高度な分析・レポート" },
			{ id: "mobile_app", label: "ネイティブアプリ対応" },
			{ id: "large_migration", label: "大規模なデータ移行" },
		],
		freeTextLabel: "後回しの理由、次フェーズ条件",
	},
	{
		id: "spec_priority",
		outputType: "SPEC",
		section: "スコープ・優先度",
		title: "優先順位の基準",
		prompt: "要件の優先順位をどう決めますか。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "user_value", label: "利用者価値が高いものを優先する" },
			{ id: "business_value", label: "事業成果に直結するものを優先する" },
			{ id: "risk", label: "リスクが高いものを先に検証する" },
			{ id: "dependency", label: "依存関係の土台になるものを優先する" },
			{ id: "quick_win", label: "短期間で効果が出るものを優先する" },
			{ id: "operation_load", label: "運用負荷を下げるものを優先する" },
		],
		freeTextLabel: "Must / Should / Could、判断基準",
	},
	{
		id: "spec_requirement_depth",
		outputType: "SPEC",
		section: "スコープ・優先度",
		title: "要件の粒度",
		prompt: "どの粒度まで決めますか。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "mvp", label: "MVP範囲を決める", partIds: ["scope"] },
			{ id: "screen", label: "画面ごとに決める", partIds: ["requirements"] },
			{ id: "data", label: "データや権限まで決める", partIds: ["requirements", "verification"] },
			{ id: "release", label: "リリース条件や検証方法まで決める", partIds: ["verification"] },
		],
		freeTextLabel: "含めたい範囲、含めない範囲",
	},
	{
		id: "spec_core_features",
		outputType: "SPEC",
		section: "機能・画面",
		title: "主要機能",
		prompt: "中心となる機能を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "content", label: "コンテンツ表示・詳細ページ" },
			{ id: "form", label: "入力フォーム・確認・送信" },
			{ id: "auth", label: "ログイン・会員登録・権限管理" },
			{ id: "dashboard", label: "ダッシュボード・一覧表示" },
			{ id: "crud", label: "データの作成・更新・削除" },
			{ id: "workflow", label: "承認・ステータス管理" },
			{ id: "search", label: "検索・フィルタ・ソート" },
			{ id: "import_export", label: "インポート・エクスポート" },
			{ id: "integration", label: "外部連携・Webhook" },
		],
		freeTextLabel: "必須機能、任意機能、補足",
	},
	{
		id: "spec_screens",
		outputType: "SPEC",
		section: "機能・画面",
		title: "必要な画面",
		prompt: "必要になりそうな画面を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "top", label: "トップ / ランディング" },
			{ id: "list", label: "一覧 / 検索結果" },
			{ id: "detail", label: "詳細" },
			{ id: "form", label: "入力 / 編集" },
			{ id: "confirm", label: "確認 / 完了" },
			{ id: "login", label: "ログイン / アカウント" },
			{ id: "dashboard", label: "ダッシュボード" },
			{ id: "settings", label: "設定" },
			{ id: "error", label: "エラー / 権限なし" },
		],
		freeTextLabel: "画面名、画面間遷移、不要な画面",
	},
	{
		id: "spec_interaction",
		outputType: "SPEC",
		section: "機能・画面",
		title: "操作と状態変化",
		prompt: "明確に定義したい操作や状態変化を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "validation", label: "入力チェックとエラー表示" },
			{ id: "draft", label: "下書き保存・途中再開" },
			{ id: "status", label: "ステータス遷移" },
			{ id: "empty_loading_error", label: "空・読込中・失敗時の表示" },
			{ id: "bulk", label: "一括操作" },
			{ id: "undo", label: "取り消し・復元" },
			{ id: "permission_state", label: "権限による表示・操作制御" },
		],
		freeTextLabel: "操作前後の状態、例外、エラー文言",
	},
	{
		id: "spec_data_entities",
		outputType: "SPEC",
		section: "データ・権限",
		title: "扱うデータ",
		prompt: "主に扱うデータの種類を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "user", label: "ユーザー・アカウント" },
			{ id: "content", label: "記事・ページ・コンテンツ" },
			{ id: "product", label: "商品・プラン・メニュー" },
			{ id: "order", label: "注文・予約・申込" },
			{ id: "message", label: "問い合わせ・メッセージ" },
			{ id: "file", label: "画像・ファイル" },
			{ id: "log", label: "ログ・履歴・分析データ" },
			{ id: "external_data", label: "外部サービス由来のデータ" },
		],
		freeTextLabel: "データ項目、必須項目、保持期間",
	},
	{
		id: "spec_permissions",
		outputType: "SPEC",
		section: "データ・権限",
		title: "権限・ロール",
		prompt: "権限やロールの要件を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "guest", label: "未ログイン閲覧者" },
			{ id: "member", label: "一般ユーザー" },
			{ id: "editor", label: "編集者・担当者" },
			{ id: "admin", label: "管理者" },
			{ id: "owner", label: "オーナー・組織管理者" },
			{ id: "api_client", label: "APIクライアント" },
			{ id: "role_matrix", label: "権限表が必要" },
		],
		freeTextLabel: "ロール別にできること、禁止する操作",
	},
	{
		id: "spec_data_handling",
		outputType: "SPEC",
		section: "データ・権限",
		title: "データ管理",
		prompt: "データ管理上の要件を選択してください。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "audit", label: "変更履歴・監査ログを残す" },
			{ id: "backup", label: "バックアップ・復元を考慮する" },
			{ id: "migration", label: "既存データ移行がある" },
			{ id: "retention", label: "保存期間・削除ルールがある" },
			{ id: "pii", label: "個人情報や機密情報を扱う" },
			{ id: "export", label: "CSVや外部形式で出力する" },
		],
		freeTextLabel: "保持期間、削除条件、監査要件",
	},
	{
		id: "spec_non_functional",
		outputType: "SPEC",
		section: "非機能・制約",
		title: "非機能要件",
		prompt: "重視する非機能要件を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "performance", label: "表示速度・応答速度" },
			{ id: "availability", label: "可用性・障害時の継続性" },
			{ id: "security", label: "セキュリティ" },
			{ id: "accessibility", label: "アクセシビリティ" },
			{ id: "seo", label: "SEO / OGP" },
			{ id: "responsive", label: "レスポンシブ対応" },
			{ id: "maintainability", label: "保守性・拡張性" },
			{ id: "observability", label: "ログ・監視・計測" },
		],
		freeTextLabel: "目標値、対象デバイス、品質基準",
	},
	{
		id: "spec_constraints",
		outputType: "SPEC",
		section: "非機能・制約",
		title: "制約条件",
		prompt: "前提となる制約を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "deadline", label: "期限が決まっている" },
			{ id: "budget", label: "予算・工数に上限がある" },
			{ id: "tech_stack", label: "使う技術が決まっている" },
			{ id: "existing_system", label: "既存システムとの整合が必要" },
			{ id: "brand", label: "ブランド・デザインルールがある" },
			{ id: "legal", label: "法務・規約・審査がある" },
			{ id: "operation", label: "運用体制に制約がある" },
		],
		freeTextLabel: "期限、予算、既存前提、禁止事項",
	},
	{
		id: "spec_integration",
		outputType: "SPEC",
		section: "非機能・制約",
		title: "外部連携",
		prompt: "外部サービスや既存システムとの連携を選択してください。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "payment", label: "決済" },
			{ id: "mail", label: "メール配信" },
			{ id: "crm", label: "CRM / MA" },
			{ id: "cms", label: "CMS" },
			{ id: "storage", label: "ファイルストレージ" },
			{ id: "analytics", label: "分析・タグ管理" },
			{ id: "auth_provider", label: "外部認証" },
			{ id: "api", label: "外部API" },
		],
		freeTextLabel: "サービス名、連携方向、失敗時の扱い",
	},
	{
		id: "spec_usecase_website",
		outputType: "SPEC",
		section: "用途別設問",
		title: "Webサイト / LPで決めること",
		prompt: "WebサイトやLPに該当する場合、必要な論点を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "message", label: "ファーストビューで伝える訴求" },
			{ id: "sections", label: "必要なセクション構成" },
			{ id: "cta", label: "CTAとコンバージョン導線" },
			{ id: "content_owner", label: "更新担当と更新頻度" },
			{ id: "seo", label: "SEO対象キーワードやOGP" },
			{ id: "form", label: "問い合わせ・資料請求フォーム" },
		],
		freeTextLabel: "ページ構成、CTA、計測したい成果",
	},
	{
		id: "spec_usecase_app",
		outputType: "SPEC",
		section: "用途別設問",
		title: "Webアプリ / 管理画面で決めること",
		prompt: "Webアプリや管理画面に該当する場合、必要な論点を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "roles", label: "ロール別の操作範囲" },
			{ id: "crud", label: "主要データのCRUD" },
			{ id: "workflow", label: "ステータス・承認フロー" },
			{ id: "dashboard", label: "一覧・ダッシュボードの指標" },
			{ id: "notification", label: "通知条件" },
			{ id: "audit", label: "操作履歴・監査ログ" },
		],
		freeTextLabel: "主要オブジェクト、ロール、業務フロー",
	},
	{
		id: "spec_usecase_commerce",
		outputType: "SPEC",
		section: "用途別設問",
		title: "EC / 予約 / 申込で決めること",
		prompt: "EC、予約、申込に該当する場合、必要な論点を選択してください。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "catalog", label: "商品・プラン・枠の管理" },
			{ id: "cart", label: "カート・申込ステップ" },
			{ id: "payment", label: "決済・請求・返金" },
			{ id: "inventory", label: "在庫・予約枠・上限数" },
			{ id: "mail", label: "確認メール・通知" },
			{ id: "cancel", label: "キャンセル・変更・期限" },
		],
		freeTextLabel: "販売対象、決済条件、キャンセルルール",
	},
	{
		id: "spec_usecase_ai_api",
		outputType: "SPEC",
		section: "用途別設問",
		title: "AI / APIで決めること",
		prompt: "AIツールやAPIに該当する場合、必要な論点を選択してください。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "input", label: "入力データと前処理" },
			{ id: "output", label: "出力形式と品質基準" },
			{ id: "fallback", label: "失敗時・低品質時の扱い" },
			{ id: "rate_limit", label: "レート制限・利用上限" },
			{ id: "auth", label: "認証・認可" },
			{ id: "logging", label: "ログ・トレース・監視" },
			{ id: "versioning", label: "バージョン管理" },
		],
		freeTextLabel: "入力例、出力例、エラー条件",
	},
	{
		id: "spec_acceptance",
		outputType: "SPEC",
		section: "検証・リリース",
		title: "受け入れ条件",
		prompt: "完成判定に必要な受け入れ条件を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "user_flow", label: "主要ユーザーフローが完了できる" },
			{ id: "required_data", label: "必須データが正しく保存・表示される" },
			{ id: "permission", label: "権限ごとの表示・操作が正しい" },
			{ id: "error", label: "エラーや例外時の表示が定義通り" },
			{ id: "responsive", label: "主要デバイスで破綻しない" },
			{ id: "performance", label: "速度や応答時間の基準を満たす" },
			{ id: "security", label: "セキュリティ上の確認を通過する" },
		],
		freeTextLabel: "完了条件、NG条件、レビュー観点",
	},
	{
		id: "spec_testing",
		outputType: "SPEC",
		section: "検証・リリース",
		title: "検証方法",
		prompt: "どの方法で検証しますか。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "unit", label: "単体テスト" },
			{ id: "integration", label: "結合テスト" },
			{ id: "e2e", label: "E2Eテスト" },
			{ id: "manual", label: "手動確認" },
			{ id: "visual", label: "表示・レスポンシブ確認" },
			{ id: "security", label: "セキュリティ確認" },
			{ id: "user_review", label: "関係者レビュー・ユーザーテスト" },
		],
		freeTextLabel: "確認環境、テストデータ、担当者",
	},
	{
		id: "spec_release",
		outputType: "SPEC",
		section: "検証・リリース",
		title: "リリース・運用",
		prompt: "リリースや運用で決めるべきことを選択してください。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "staging", label: "ステージング確認" },
			{ id: "migration", label: "データ移行・初期投入" },
			{ id: "rollback", label: "ロールバック手順" },
			{ id: "monitoring", label: "監視・アラート" },
			{ id: "manual", label: "運用マニュアル" },
			{ id: "handover", label: "引き継ぎ・権限付与" },
			{ id: "post_release", label: "公開後の改善サイクル" },
		],
		freeTextLabel: "公開日、運用担当、初期データ",
	},
	{
		id: "Q-intent-01",
		outputType: "DESIGN",
		section: "目的・対象",
		layer: "intent",
		title: "サイトの目的",
		prompt: "",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "a", label: "コーポレート（企業情報・ブランド発信）", partIds: ["design_direction"] },
			{ id: "b", label: "LP・プロモーション（製品/イベント告知）", partIds: ["design_direction"] },
			{ id: "c", label: "EC・販売", partIds: ["design_direction"] },
			{ id: "d", label: "ポートフォリオ・作品集", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-intent-02",
		outputType: "DESIGN",
		section: "目的・対象",
		layer: "intent",
		title: "主な対象者",
		prompt: "",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "a", label: "10代〜20代前半（若年層）", partIds: ["design_direction"] },
			{ id: "b", label: "20代後半〜30代（中堅層）", partIds: ["design_direction"] },
			{ id: "c", label: "40代以上（成熟層）", partIds: ["design_direction"] },
			{ id: "d", label: "業界プロ・専門家（年齢不問）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-intent-03",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "intent",
		title: "第一印象",
		prompt: "訪問直後に伝えたい印象を選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "a", label: "信頼感・誠実", partIds: ["design_direction"] },
			{ id: "b", label: "神秘性・特別感", partIds: ["design_direction"] },
			{ id: "c", label: "楽しさ・遊び心", partIds: ["design_direction"] },
			{ id: "d", label: "静けさ・余白", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-intent-04",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "intent",
		title: "避けたい表現",
		prompt: "同業・類似サイトで使われやすい表現のうち、避けたいものを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "ありきたりな透明感・明るさ", partIds: ["design_direction"] },
			{ id: "b", label: "過剰な装飾・エフェクト", partIds: ["design_direction"] },
			{ id: "c", label: "冷たすぎる無機質さ", partIds: ["design_direction"] },
			{ id: "d", label: "特に避けたい表現はない", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-mood-01",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "mood",
		title: "サイト全体の明るさ",
		prompt: "",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "a", label: "暗色ベース（黒〜深い色を背景に）", partIds: ["design_direction"] },
			{ id: "b", label: "明色ベース（白〜淡い色を背景に）", partIds: ["design_direction"] },
			{ id: "c", label: "中間（グレー・ベージュ等の中明度）", partIds: ["design_direction"] },
			{ id: "d", label: "グラデーション主体", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-mood-02",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "mood",
		title: "配色の温度感",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "暖色寄り（赤・オレンジ・ベージュ・ピンク）", partIds: ["design_direction"] },
			{ id: "b", label: "寒色寄り（青・緑・紫）", partIds: ["design_direction"] },
			{ id: "c", label: "中性（モノクロ・グレー・無彩色）", partIds: ["design_direction"] },
			{ id: "d", label: "暖寒の対比（両極を意図的に組む）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-mood-04",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "mood",
		title: "サイト全体の印象",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "堅実・信頼感を重視", partIds: ["design_direction"] },
			{ id: "b", label: "親しみやすさを重視", partIds: ["design_direction"] },
			{ id: "c", label: "洗練・上品さを重視", partIds: ["design_direction"] },
			{ id: "d", label: "先進性・技術感を重視", partIds: ["design_direction"] },
			{ id: "e", label: "大胆さ・記憶への残りやすさを重視", partIds: ["design_direction"] },
			{ id: "f", label: "落ち着き・余白を重視", partIds: ["design_direction"] },
			{ id: "g", label: "遊び心・ユーモアを重視", partIds: ["design_direction"] },
			{ id: "h", label: "実用性・わかりやすさを重視", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-visual-01",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "visual",
		title: "配色構成",
		prompt: "",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "a", label: "モノクロ（無彩色のみ）", partIds: ["design_direction"] },
			{ id: "b", label: "2色構成（メイン + 差し色1色）", partIds: ["design_direction"] },
			{ id: "c", label: "多色（3色以上の意図的なパレット）", partIds: ["design_direction"] },
			{ id: "d", label: "グラデーション主体", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-visual-02",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "visual",
		title: "アクセントカラーの扱い",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "単一の差し色を強く効かせる", partIds: ["design_direction"] },
			{ id: "b", label: "2色のアクセント（主・副）を使い分け", partIds: ["design_direction"] },
			{ id: "c", label: "差し色なし（モノトーンで完結）", partIds: ["design_direction"] },
			{ id: "d", label: "グラデーションアクセント", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-visual-03",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "visual",
		title: "全体の質感",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "マット（フラット・影なし）", partIds: ["design_direction"] },
			{ id: "b", label: "光沢（反射・ハイライトを強調）", partIds: ["design_direction"] },
			{ id: "c", label: "紙質（繊維感・印刷物のような質感）", partIds: ["design_direction"] },
			{ id: "d", label: "布・織物（柔らかい表面感）", partIds: ["design_direction"] },
			{ id: "e", label: "金属（硬質・反射・精密感）", partIds: ["design_direction"] },
			{ id: "f", label: "ガラス（透過・ぼかし・屈折感）", partIds: ["design_direction"] },
			{ id: "g", label: "粒状ノイズ（ざらつき・フィルム感）", partIds: ["design_direction"] },
			{ id: "h", label: "立体的な陰影（奥行き・浮遊感）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-type-01",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "typography",
		title: "文字組みの主軸",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "serif / 明朝 主役", partIds: ["design_direction"] },
			{ id: "b", label: "sans / ゴシック 主役", partIds: ["design_direction"] },
			{ id: "c", label: "混在（見出しserif + 本文sans 等）", partIds: ["design_direction"] },
			{ id: "d", label: "装飾的（手書き・display・特殊フォント）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-type-02",
		outputType: "DESIGN",
		section: "色・文字・質感",
		layer: "typography",
		title: "日本語フォントの系統",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "明朝（伝統・上品・editorial）", partIds: ["design_direction"] },
			{ id: "b", label: "ゴシック（現代・読みやすさ・実用）", partIds: ["design_direction"] },
			{ id: "c", label: "丸ゴシック（親しみやすい・rounded）", partIds: ["design_direction"] },
			{ id: "d", label: "日本語フォント不要（英字のみで完結）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-motion-01",
		outputType: "DESIGN",
		section: "動き・演出",
		layer: "motion",
		title: "アニメーションのテンポ",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "素早い（0.2s前後・反応早く軽快）", partIds: ["design_direction"] },
			{ id: "b", label: "中庸（0.4〜0.8s・標準的）", partIds: ["design_direction"] },
			{ id: "c", label: "ゆったり（1.5〜2s・余裕・贅沢）", partIds: ["design_direction"] },
			{ id: "d", label: "アニメ最小限（必要箇所のみ・無くてもOK）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-motion-03",
		outputType: "DESIGN",
		section: "動き・演出",
		layer: "motion",
		title: "アニメーション実装の許容範囲",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "CSS + IntersectionObserver のみ（外部依存ゼロ）", partIds: ["design_direction"] },
			{ id: "b", label: "GSAP 系を許容", partIds: ["design_direction"] },
			{ id: "c", label: "WebGL / Three.js も含めて自由", partIds: ["design_direction"] },
			{ id: "d", label: "必要最小限（要件次第で都度判断）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-component-02",
		outputType: "DESIGN",
		section: "UIパーツ・操作感",
		layer: "component",
		title: "必須パーツ",
		prompt: "必要なUIパーツまたはセクション要素を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "a", label: "入場演出系（page-loader / opening-sequence / page-transition）", partIds: ["design_direction"] },
			{ id: "b", label: "ナビ系（nav-header / nav-link / sp-menu）", partIds: ["design_direction"] },
			{ id: "c", label: "KV系（kv-hero / hero-title / scroll-indicator）", partIds: ["design_direction"] },
			{ id: "d", label: "コンテンツ系（section-heading / card-item / cta-button）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力で個別パーツ名を列挙）",
	},
	{
		id: "Q-tech-01",
		outputType: "DESIGN",
		section: "技術・制約",
		layer: "technical",
		title: "優先デバイス",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "モバイル優先（SP UX が最重要）", partIds: ["design_direction"] },
			{ id: "b", label: "デスクトップ優先（PC UX が最重要）", partIds: ["design_direction"] },
			{ id: "c", label: "両立（SP/PC 等しく作り込む）", partIds: ["design_direction"] },
			{ id: "d", label: "SP 専用（PC 表示は最低限）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-tech-02",
		outputType: "DESIGN",
		section: "技術・制約",
		layer: "technical",
		title: "外部ライブラリ・サービスの許容範囲",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "依存ゼロ（CDN含めて外部リソース禁止）", partIds: ["design_direction"] },
			{ id: "b", label: "限定的（Google Fonts / 軽量CDNのみ可）", partIds: ["design_direction"] },
			{ id: "c", label: "自由（GSAP / Three.js 等含めて目的次第）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-corporate-01",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "corporate",
		title: "会社の見せ方",
		prompt: "会社の現在の状態を、訪問者にどのように認識させたいか選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "堅実に成長している", partIds: ["design_direction"] },
			{ id: "b", label: "変革期にある", partIds: ["design_direction"] },
			{ id: "c", label: "新しく挑戦している", partIds: ["design_direction"] },
			{ id: "d", label: "成熟した専門家集団", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-corporate-02",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "corporate",
		title: "信頼の根拠",
		prompt: "信頼形成のために優先して見せたい情報を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "実績", partIds: ["design_direction"] },
			{ id: "b", label: "導入事例", partIds: ["design_direction"] },
			{ id: "c", label: "技術力", partIds: ["design_direction"] },
			{ id: "d", label: "人", partIds: ["design_direction"] },
			{ id: "e", label: "歴史", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-corporate-03",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "corporate",
		title: "優先情報",
		prompt: "訪問者に優先して読ませたい情報を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "a", label: "事業内容", partIds: ["design_direction"] },
			{ id: "b", label: "導入事例・実績", partIds: ["design_direction"] },
			{ id: "c", label: "採用情報", partIds: ["design_direction"] },
			{ id: "d", label: "会社概要・代表メッセージ", partIds: ["design_direction"] },
			{ id: "e", label: "問い合わせ導線", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-corporate-05",
		outputType: "DESIGN",
		section: "目的・対象",
		layer: "corporate",
		title: "最重視するステークホルダー",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "顧客", partIds: ["design_direction"] },
			{ id: "b", label: "採用候補者", partIds: ["design_direction"] },
			{ id: "c", label: "投資家・パートナー", partIds: ["design_direction"] },
			{ id: "d", label: "既存社員", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-lp-01",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "lp",
		title: "LPの訴求対象",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "商品・サービス", partIds: ["design_direction"] },
			{ id: "b", label: "イベント・キャンペーン", partIds: ["design_direction"] },
			{ id: "c", label: "ブランド・世界観", partIds: ["design_direction"] },
			{ id: "d", label: "採用・説明会", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-lp-02",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "lp",
		title: "コンバージョンの種類",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "購入", partIds: ["design_direction"] },
			{ id: "b", label: "問い合わせ", partIds: ["design_direction"] },
			{ id: "c", label: "資料請求", partIds: ["design_direction"] },
			{ id: "d", label: "予約・申込", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-lp-03",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "lp",
		title: "LPの公開文脈",
		prompt: "常設、期間限定、イベント、新商品など、訴求の前提を選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "常設", partIds: ["design_direction"] },
			{ id: "b", label: "期間限定", partIds: ["design_direction"] },
			{ id: "c", label: "イベント", partIds: ["design_direction"] },
			{ id: "d", label: "新商品", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-lp-04",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "lp",
		title: "訴求の根拠",
		prompt: "訪問者の納得を得るために重視する根拠を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "a", label: "機能・性能", partIds: ["design_direction"] },
			{ id: "b", label: "実績・証拠", partIds: ["design_direction"] },
			{ id: "c", label: "感情・共感", partIds: ["design_direction"] },
			{ id: "d", label: "価格・お得感", partIds: ["design_direction"] },
			{ id: "e", label: "限定性・緊急性", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-lp-05",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "lp",
		title: "訴求ストーリー",
		prompt: "訪問者を理解、納得、行動へ進める順序を選択してください。",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "課題提示 → 解決策 → 証拠 → CTA", partIds: ["design_direction"] },
			{ id: "b", label: "世界観 → 商品理解 → 利用シーン → CTA", partIds: ["design_direction"] },
			{ id: "c", label: "ベネフィット → 詳細 → 比較 → CTA", partIds: ["design_direction"] },
			{ id: "d", label: "キャンペーン訴求 → 限定性 → 申込", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-ec-01",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "ec",
		title: "商品数",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "単品", partIds: ["design_direction"] },
			{ id: "b", label: "少数", partIds: ["design_direction"] },
			{ id: "c", label: "多数", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-ec-02",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "ec",
		title: "購入行動の中心",
		prompt: "探索型、指名買い、比較型のうち、主な購入行動を選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "探索型", partIds: ["design_direction"] },
			{ id: "b", label: "指名買い", partIds: ["design_direction"] },
			{ id: "c", label: "比較型", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-ec-03",
		outputType: "DESIGN",
		section: "UIパーツ・操作感",
		layer: "ec",
		title: "購入前の不安解消",
		prompt: "購入前の不安を減らすために必要な情報を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "返品・保証", partIds: ["design_direction"] },
			{ id: "b", label: "レビュー", partIds: ["design_direction"] },
			{ id: "c", label: "配送", partIds: ["design_direction"] },
			{ id: "d", label: "素材・仕様", partIds: ["design_direction"] },
			{ id: "e", label: "支払い安全性", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-ec-04",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "ec",
		title: "ECで優先する訴求要素",
		prompt: "商品写真、ブランド世界観、価格訴求などのうち、最も優先する要素を選択してください。",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "商品写真を最優先", partIds: ["design_direction"] },
			{ id: "b", label: "ブランド世界観を最優先", partIds: ["design_direction"] },
			{ id: "c", label: "価格・キャンペーン訴求を最優先", partIds: ["design_direction"] },
			{ id: "d", label: "レビュー・安心材料を最優先", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-portfolio-01",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "portfolio",
		title: "ポートフォリオの主体",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "デザイナー", partIds: ["design_direction"] },
			{ id: "b", label: "エンジニア", partIds: ["design_direction"] },
			{ id: "c", label: "クリエイター", partIds: ["design_direction"] },
			{ id: "d", label: "チーム・会社", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-portfolio-02",
		outputType: "DESIGN",
		section: "用途別設問",
		layer: "portfolio",
		title: "実力の証明",
		prompt: "実力を示すために見せたい情報を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "a", label: "完成作品", partIds: ["design_direction"] },
			{ id: "b", label: "制作プロセス", partIds: ["design_direction"] },
			{ id: "c", label: "成果数値", partIds: ["design_direction"] },
			{ id: "d", label: "推薦・評価", partIds: ["design_direction"] },
			{ id: "e", label: "思想・文章", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-portfolio-03",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "portfolio",
		title: "作品表示の重点",
		prompt: "一覧性、詳細情報、制作ストーリーのうち、重視する方向を選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "一覧", partIds: ["design_direction"] },
			{ id: "b", label: "詳細", partIds: ["design_direction"] },
			{ id: "c", label: "ストーリー", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-01",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "expression",
		title: "記憶に残したい要素",
		prompt: "訪問後に最も記憶へ残したい要素を選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "ブランド名・社名", partIds: ["design_direction"] },
			{ id: "b", label: "独自の世界観", partIds: ["design_direction"] },
			{ id: "c", label: "信頼できる理由", partIds: ["design_direction"] },
			{ id: "d", label: "具体的な行動", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-02",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "expression",
		title: "想起させたい感情",
		prompt: "訪問者に想起させたい感情を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "安心", partIds: ["design_direction"] },
			{ id: "b", label: "期待", partIds: ["design_direction"] },
			{ id: "c", label: "高揚", partIds: ["design_direction"] },
			{ id: "d", label: "知的", partIds: ["design_direction"] },
			{ id: "e", label: "親近感", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-03",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "expression",
		title: "視覚的な対比",
		prompt: "要素間の対比を強く出すか、全体になじませるかを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "強い対比", partIds: ["design_direction"] },
			{ id: "b", label: "中間", partIds: ["design_direction"] },
			{ id: "c", label: "なじませる", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-04",
		outputType: "DESIGN",
		section: "構成・情報設計",
		layer: "expression",
		title: "情報密度",
		prompt: "",
		inputType: "single",
		volume: ["deep"],
		options: [
			{ id: "a", label: "余白多め・要点をゆっくり読ませる（低密度寄り）", partIds: ["design_direction"] },
			{ id: "b", label: "標準・バランス型", partIds: ["design_direction"] },
			{ id: "c", label: "詰め気味・一覧性とスキャンしやすさ重視（中〜高密度寄り）", partIds: ["design_direction"] },
			{ id: "d", label: "情報量最優先・できるだけコンパクト（高密度寄り）", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-05",
		outputType: "DESIGN",
		section: "動き・演出",
		layer: "expression",
		title: "動きの役割",
		prompt: "",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "a", label: "ほぼ不要", partIds: ["design_direction"] },
			{ id: "b", label: "理解を助ける", partIds: ["design_direction"] },
			{ id: "c", label: "印象を残す", partIds: ["design_direction"] },
			{ id: "d", label: "操作感を高める", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "Q-expression-06",
		outputType: "DESIGN",
		section: "印象・世界観",
		layer: "expression",
		title: "避けたい見た目の失敗",
		prompt: "",
		inputType: "multi",
		volume: ["deep"],
		options: [
			{ id: "a", label: "安っぽく見える", partIds: ["design_direction"] },
			{ id: "b", label: "情報が読みにくい", partIds: ["design_direction"] },
			{ id: "c", label: "既視感が強い", partIds: ["design_direction"] },
			{ id: "d", label: "演出が重い・邪魔", partIds: ["design_direction"] },
			{ id: "e", label: "ターゲットに幼く見える", partIds: ["design_direction"] },
		],
		freeTextLabel: "その他（自由入力）",
	},
	{
		id: "agents_principles_behavior",
		outputType: "AGENTS",
		section: "行動原則",
		title: "行動原則",
		prompt: "エージェントの基本的な行動原則を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "security_first", label: "セキュリティを最優先する" },
			{ id: "user_goal", label: "依頼の目的達成を最優先する" },
			{ id: "japanese", label: "回答は日本語で行う" },
			{ id: "concise", label: "必要な情報を簡潔に伝える" },
			{ id: "explain_tradeoffs", label: "判断理由とトレードオフを明確にする" },
			{ id: "ask_when_blocked", label: "前提が足りない場合だけ確認する" },
			{ id: "no_year_search", label: "Web検索では年号を含めない" },
		],
		freeTextLabel: "優先順位、例外",
	},
	{
		id: "agents_principles_git",
		outputType: "AGENTS",
		section: "行動原則",
		title: "Git運用",
		prompt: "変更の記録と共有に関する方針を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "no_auto_commit", label: "小さな修正ごとに自動commitしない" },
			{ id: "meaningful_commit", label: "意味のある作業単位でcommitする" },
			{ id: "pr_ready_commit", label: "PRに出せるまとまりでcommitする" },
			{ id: "push_when_needed", label: "pushは共有が必要な時に行う" },
		],
		freeTextLabel: "commit粒度、push条件",
	},
	{
		id: "agents_principles_test_policy",
		outputType: "AGENTS",
		section: "行動原則",
		title: "テスト方針",
		prompt: "品質確認の基準を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "coverage_80", label: "最小カバレッジ80%を維持する" },
			{ id: "risk_based", label: "影響範囲とリスクに応じてテストする" },
			{ id: "document_gap", label: "未実行の確認項目は報告する" },
		],
		freeTextLabel: "必須テスト、除外条件",
	},
	{
		id: "agents_tech_ui_runtime",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "UIライブラリ / フレームワーク",
		prompt: "UI実装の中心に置くライブラリまたはフレームワークを選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "react", label: "React" },
			{ id: "vue", label: "Vue" },
			{ id: "svelte", label: "Svelte" },
			{ id: "angular", label: "Angular" },
			{ id: "solid", label: "Solid" },
			{ id: "preact", label: "Preact" },
			{ id: "astro", label: "Astro" },
			{ id: "next", label: "Next.js" },
			{ id: "nuxt", label: "Nuxt" },
		],
		freeTextLabel: "バージョン、併用条件、除外する候補",
	},
	{
		id: "agents_tech_build_tool",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "ビルドツール",
		prompt: "開発サーバーとビルドの基盤を選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "vite", label: "Vite" },
			{ id: "webpack", label: "webpack" },
			{ id: "turbopack", label: "Turbopack" },
			{ id: "rollup", label: "Rollup" },
			{ id: "parcel", label: "Parcel" },
			{ id: "esbuild", label: "esbuild" },
			{ id: "rsbuild", label: "Rsbuild" },
		],
		freeTextLabel: "バージョン、開発サーバー条件、除外する候補",
	},
	{
		id: "agents_tech_language",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "実装言語",
		prompt: "アプリケーションコードの主言語を選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "typescript", label: "TypeScript" },
			{ id: "javascript", label: "JavaScript" },
			{ id: "flow", label: "Flow" },
			{ id: "rescript", label: "ReScript" },
			{ id: "elm", label: "Elm" },
		],
		freeTextLabel: "型チェック条件、生成コード、例外",
	},
	{
		id: "agents_tech_styling",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "スタイリング",
		prompt: "スタイル定義の基盤を選択してください。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "sass", label: "Sass" },
			{ id: "customclass", label: "CustomClass" },
			{ id: "tailwind", label: "Tailwind CSS" },
			{ id: "css_modules", label: "CSS Modules" },
			{ id: "css_in_js", label: "CSS-in-JS" },
			{ id: "vanilla_css", label: "Vanilla CSS" },
			{ id: "no_unapproved_framework", label: "未承認のスタイル基盤は追加しない" },
		],
		freeTextLabel: "併用条件、禁止する書き方、補足",
	},
	{
		id: "agents_tech_routing",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "ルーティング方式 / ライブラリ",
		prompt: "ルーティングの定義方式またはライブラリを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "react_router", label: "react-router-dom" },
			{ id: "file_based", label: "ファイルベースルーティング" },
			{ id: "config_based", label: "設定ベースルーティング" },
			{ id: "hash", label: "ハッシュルーティング" },
			{ id: "none", label: "ルーティングなし" },
		],
		freeTextLabel: "URL設計、ネスト、遷移制約",
	},
	{
		id: "agents_tech_test",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "テスト",
		prompt: "テスト環境として指定するものを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "vitest_happy_dom", label: "Vitest（happy-dom）" },
			{ id: "vitest", label: "Vitest" },
			{ id: "jest", label: "Jest" },
			{ id: "playwright", label: "Playwright" },
			{ id: "none", label: "未定義" },
		],
		freeTextLabel: "カバレッジ、実行条件、補足",
	},
	{
		id: "agents_tech_state",
		outputType: "AGENTS",
		section: "技術スタック",
		title: "状態管理",
		prompt: "状態管理の基本方針を選択してください。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "react_builtin", label: "React組み込み" },
			{ id: "router_state", label: "React Router" },
			{ id: "zustand", label: "Zustand" },
			{ id: "redux", label: "Redux Toolkit" },
			{ id: "jotai", label: "Jotai" },
			{ id: "avoid_global", label: "不要なグローバル状態を追加しない" },
		],
		freeTextLabel: "許可する状態管理ライブラリ、禁止する状態配置",
	},
	{
		id: "agents_command_dev",
		outputType: "AGENTS",
		section: "コマンド",
		title: "開発サーバー",
		prompt: "開発サーバーの起動コマンドを選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "npm_run_dev", label: "`npm run dev`" },
			{ id: "npm_run_dev_port_3000", label: "`npm run dev` / port 3000" },
			{ id: "pnpm_dev", label: "`pnpm dev`" },
			{ id: "yarn_dev", label: "`yarn dev`" },
		],
		freeTextLabel: "ポート、環境変数、補足",
	},
	{
		id: "agents_command_build",
		outputType: "AGENTS",
		section: "コマンド",
		title: "プロダクションビルド",
		prompt: "プロダクションビルドのコマンドを選択してください。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "npm_run_build", label: "`npm run build`" },
			{ id: "pnpm_build", label: "`pnpm build`" },
			{ id: "yarn_build", label: "`yarn build`" },
			{ id: "condition_limited", label: "API・状態管理・認証・ロジック変更時" },
		],
		freeTextLabel: "実行条件、補足",
	},
	{
		id: "agents_command_preview",
		outputType: "AGENTS",
		section: "コマンド",
		title: "ビルドプレビュー",
		prompt: "ビルド結果のプレビューコマンドを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "npm_run_preview", label: "`npm run preview`" },
			{ id: "pnpm_preview", label: "`pnpm preview`" },
			{ id: "yarn_preview", label: "`yarn preview`" },
			{ id: "condition_manual", label: "表示確認が必要な場合" },
		],
		freeTextLabel: "確認条件、補足",
	},
	{
		id: "agents_command_lint",
		outputType: "AGENTS",
		section: "コマンド",
		title: "Lint",
		prompt: "Lintの実行コマンドを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "npm_run_lint", label: "`npm run lint`" },
			{ id: "pnpm_lint", label: "`pnpm lint`" },
			{ id: "yarn_lint", label: "`yarn lint`" },
			{ id: "condition_related", label: "関連変更がある場合" },
		],
		freeTextLabel: "実行条件、補足",
	},
	{
		id: "agents_command_test",
		outputType: "AGENTS",
		section: "コマンド",
		title: "テスト",
		prompt: "テストの実行コマンドを選択してください。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "npm_test", label: "`npm test`" },
			{ id: "pnpm_test", label: "`pnpm test`" },
			{ id: "yarn_test", label: "`yarn test`" },
			{ id: "coverage_80", label: "カバレッジ80%以上" },
			{ id: "condition_impact", label: "影響範囲に応じる" },
		],
		freeTextLabel: "テスト条件、補足",
	},
	{
		id: "agents_coding_rules",
		outputType: "AGENTS",
		section: "コーディング規約",
		title: "コーディング規約",
		prompt: "コードを書く時に守らせたい規約を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "function_hooks", label: "関数コンポーネントとhooksを基本にする" },
			{ id: "props_interface", label: "Props型はinterfaceで定義する" },
			{ id: "component_pascal", label: "コンポーネント名はPascalCaseにする" },
			{ id: "module_camel", label: "モジュール名と関数名はcamelCaseにする" },
			{ id: "hook_use_prefix", label: "カスタムフックはuseプレフィックスにする" },
			{ id: "class_snake", label: "CSSクラス名はsnake_caseにする" },
			{ id: "effects_precise", label: "副作用は局所化し、依存関係を正確に保つ" },
			{ id: "semantic_html", label: "意味のあるHTMLを優先する" },
			{ id: "aria_role", label: "roleやaria-*を必要な箇所に使う" },
			{ id: "keyboard", label: "操作UIではキーボード操作を考慮する" },
			{ id: "existing_patterns", label: "既存実装のパターンに合わせる" },
		],
		freeTextLabel: "追加規約、例外、参照ルール",
	},
	{
		id: "agents_execution_rules",
		outputType: "AGENTS",
		section: "実行ルール",
		title: "実行ルール",
		prompt: "エージェントに守らせたい実行ルールを選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "read_before_edit", label: "初めて編集するファイルは先に内容を確認する" },
			{ id: "small_scope", label: "変更範囲は依頼に必要な部分へ絞る" },
			{ id: "respect_existing", label: "既存の設計と命名に合わせる" },
			{ id: "preserve_user_changes", label: "ユーザーや他者の変更を勝手に戻さない" },
			{ id: "report_blockers", label: "実行できない理由は具体的に報告する" },
			{ id: "ask_when_risky", label: "破壊的変更や判断が分かれる変更は先に確認する" },
			{ id: "verify_when_needed", label: "影響がある変更は適切な確認を行う" },
			{ id: "state_unverified", label: "確認していない内容は未確認として扱う" },
			{ id: "keep_output_concise", label: "報告は要点と結果を中心にまとめる" },
			{ id: "avoid_duplicate_work", label: "同じ目的の調査や確認を不要に繰り返さない" },
			{ id: "avoid_reread", label: "未変更の既読ファイルを再読込しない" },
			{ id: "use_fast_search", label: "検索には高速なツールを優先する" },
			{ id: "prefer_project_tools", label: "対象環境にあるツールと手順を優先する" },
			{ id: "separate_changes", label: "無関係な修正を同じ作業に混ぜない" },
			{ id: "document_test_gap", label: "未実行のテストや確認不足を明記する" },
			{ id: "protect_secrets", label: "秘密情報を出力やファイルに残さない" },
			{ id: "handle_errors", label: "エラーは原因と対応を整理して扱う" },
			{ id: "follow_latest_instruction", label: "矛盾する指示がある場合は最新の指示を優先する" },
			{ id: "avoid_unneeded_deps", label: "不要な依存関係を追加しない" },
			{ id: "avoid_unneeded_classes", label: "新規クラスや変数は必要性を確認してから作る" },
		],
		freeTextLabel: "追加ルール、優先順位、例外",
	},
	{
		id: "agents_prohibited",
		outputType: "AGENTS",
		section: "禁止事項",
		title: "禁止事項",
		prompt: "エージェントに禁止したい行動を選択してください。複数選択できます。",
		inputType: "multi",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "no_destructive_without_approval", label: "承認なしに削除・上書き・resetをしない" },
			{ id: "no_secret_exposure", label: "秘密情報や個人情報を公開しない" },
			{ id: "no_unrelated_refactor", label: "依頼外のリファクタを混ぜない" },
			{ id: "no_unrequested_commit", label: "指示なしにcommitやpushをしない" },
			{ id: "no_fake_verification", label: "実行していない確認を実行済みと言わない" },
			{ id: "no_ignore_errors", label: "エラーや警告を無視して完了扱いにしない" },
			{ id: "no_overwrite_user_work", label: "ユーザー作業を確認なく上書きしない" },
			{ id: "no_new_framework_without_need", label: "必要性なく新しい基盤を導入しない" },
			{ id: "no_large_rewrite_without_request", label: "依頼なしに大規模な書き換えをしない" },
			{ id: "no_private_path_public", label: "公開物にローカルの個人パスを書かない" },
			{ id: "no_license_risk", label: "ライセンス不明の素材やコードを混ぜない" },
			{ id: "no_security_downgrade", label: "セキュリティを弱める変更をしない" },
			{ id: "no_test_deletion", label: "理由なくテストを削除しない" },
			{ id: "no_comment_deletion", label: "承認なしに意図あるコメントを削除しない" },
			{ id: "no_format_churn", label: "無関係な整形差分を広げない" },
			{ id: "no_assume_external_state", label: "外部の最新情報を未確認で断定しない" },
			{ id: "no_hidden_side_effects", label: "副作用のある操作を黙って実行しない" },
			{ id: "no_duplicate_dependencies", label: "既存機能と重複する依存を追加しない" },
			{ id: "no_accessibility_regression", label: "アクセシビリティを退化させない" },
			{ id: "no_scope_creep", label: "相談や検討段階で実装に進まない" },
		],
		freeTextLabel: "追加の禁止事項、承認条件、例外",
	},
	{
		id: "prompt_task",
		outputType: "PROMPT",
		section: "タスク内容",
		title: "依頼するタスク",
		prompt: "AIに何を実行させますか。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "write", label: "文章作成", partIds: ["role_context", "output_contract"] },
			{ id: "analyze", label: "分析・整理", partIds: ["role_context", "question_policy"] },
			{ id: "code", label: "実装・修正", partIds: ["role_context", "output_contract"] },
			{ id: "review", label: "レビュー", partIds: ["question_policy", "output_contract"] },
		],
		freeTextLabel: "入力資料、完了条件、避けたい出力",
	},
	{
		id: "prompt_density",
		outputType: "PROMPT",
		section: "品質基準",
		title: "出力の粒度",
		prompt: "どの程度の詳しさを求めますか。",
		inputType: "single",
		volume: ["standard", "deep"],
		options: [
			{ id: "brief", label: "短く要点だけ", partIds: ["output_contract"] },
			{ id: "standard", label: "実務で使える標準粒度", partIds: ["output_contract"] },
			{ id: "detailed", label: "判断理由まで詳しく", partIds: ["question_policy", "output_contract"] },
		],
		freeTextLabel: "文体、読者、出力に含めたい見出し",
	},
	{
		id: "skill_kind",
		outputType: "PROMPT_FOR_SKILL",
		section: "対象・前提",
		title: "作りたいスキル",
		prompt: "どの種類の作業を支援するスキルを作りますか。",
		inputType: "single",
		volume: ["quick", "standard", "deep"],
		options: [
			{ id: "workflow", label: "作業手順を標準化", partIds: ["skill_trigger", "skill_workflow"] },
			{ id: "tool", label: "ツール利用を定義", partIds: ["skill_workflow", "skill_fallback"] },
			{ id: "review", label: "レビュー観点を定義", partIds: ["skill_trigger", "skill_fallback"] },
		],
		freeTextLabel: "想定ユーザー、対象ファイル、利用するツール",
	},
	{
		id: "skill_failure",
		outputType: "PROMPT_FOR_SKILL",
		section: "例外処理",
		title: "失敗時の扱い",
		prompt: "うまく進まない場合の扱いをどう指定しますか。",
		inputType: "multi",
		volume: ["standard", "deep"],
		options: [
			{ id: "ask", label: "ユーザーに確認する", partIds: ["skill_fallback"] },
			{ id: "fallback", label: "代替手順へ進む", partIds: ["skill_fallback"] },
			{ id: "stop", label: "安全のため停止する", partIds: ["skill_fallback"] },
		],
		freeTextLabel: "停止条件、確認すべき不足情報",
	},
];

const createEmptyAnswers = () =>
	questions.reduce<Record<string, QuestionAnswer>>((answers, question) => {
		answers[question.id] = {
			selectedOptionIds: [],
			freeText: "",
		};
		return answers;
	}, {});

export const createInitialState = (): DocumentDraftState => ({
	outputType: "SPEC",
	answerVolume: "standard",
	showUnansweredAnswers: false,
	globalFreeText: "",
	answers: createEmptyAnswers(),
	selectedPartIds: parts.filter((part) => part.outputType === "SPEC").map((part) => part.id),
	generatedMarkdown: "",
});
